-- WideAds · Operação BDR/SDR — configuração do banco no Supabase
-- Cole tudo no SQL Editor do seu projeto Supabase e clique em Run.

-- 1) Tabela de leads / pipeline
create table if not exists public.leads (
  id          bigint generated by default as identity primary key,
  nome        text,
  rede        text,
  vertical    text,
  regiao      text,
  fluxo       integer default 0,
  tier        text,
  score       numeric,
  motor       text,
  fonte       text,
  prioridade  text,
  sdr         text,
  stage       text default 'novo',
  perdido     boolean default false,
  obs         text default '',
  updated_at  timestamptz default now()
);

-- 2) Segurança em nível de linha (RLS): só usuários logados acessam
alter table public.leads enable row level security;

drop policy if exists "leads_select" on public.leads;
drop policy if exists "leads_insert" on public.leads;
drop policy if exists "leads_update" on public.leads;
drop policy if exists "leads_delete" on public.leads;

create policy "leads_select" on public.leads for select to authenticated using (true);
create policy "leads_insert" on public.leads for insert to authenticated with check (true);
create policy "leads_update" on public.leads for update to authenticated using (true) with check (true);
create policy "leads_delete" on public.leads for delete to authenticated using (true);

-- 3) Atualização em tempo real (o time vê as mudanças ao vivo)
do $$ begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='leads'
  ) then
    alter publication supabase_realtime add table public.leads;
  end if;
end $$;

-- 4) Administração: lista de e-mails admin master + configurações (SDR/BDR e metas)
create table if not exists public.admins (
  email text primary key
);
alter table public.admins enable row level security;
drop policy if exists "admins_select" on public.admins;
create policy "admins_select" on public.admins for select to authenticated using (true);
-- (sem policy de insert/update/delete: só você adiciona admins direto pelo SQL Editor)

create table if not exists public.settings (
  id         int primary key default 1,
  reps       jsonb default '[]'::jsonb,
  metas      jsonb default '{}'::jsonb,
  updated_at timestamptz default now()
);
insert into public.settings(id) values (1) on conflict (id) do nothing;
alter table public.settings enable row level security;
drop policy if exists "settings_select" on public.settings;
drop policy if exists "settings_update" on public.settings;
create policy "settings_select" on public.settings for select to authenticated using (true);
create policy "settings_update" on public.settings for update to authenticated
  using (auth.jwt()->>'email' in (select email from public.admins))
  with check (auth.jwt()->>'email' in (select email from public.admins));

do $$ begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='settings'
  ) then
    alter publication supabase_realtime add table public.settings;
  end if;
end $$;

-- 5) Defina aqui o(s) e-mail(s) do admin master (troque pelo seu e-mail de login)
insert into public.admins(email) values ('paulolopesjunior1@gmail.com') on conflict do nothing;
